Blacklist["Props"] = {"hei_prop_carrier_radar_1_l1", "v_res_mexball", "prop_rock_1_a", "prop_rock_1_b", "prop_rock_1_c",
                      "prop_rock_1_d", "prop_rock_1_e", "prop_rock_1_f", "prop_bikini_disp_03", "prop_rock_1_g",
                      "prop_rock_1_h", "prop_player_gasmask", "prop_test_boulder_01", "prop_test_boulder_02",
                      "prop_test_boulder_03", "prop_test_boulder_04", "ex_prop_exec_crashdp",
                      "apa_mp_apa_yacht_o1_rail_a", "apa_mp_apa_yacht_o1_rail_b", "apa_mp_h_yacht_armchair_01",
                      "apa_mp_h_yacht_armchair_03", "apa_mp_h_yacht_armchair_04", "apa_mp_h_yacht_barstool_01",
                      "apa_mp_h_yacht_bed_01", "apa_mp_h_yacht_bed_02", "apa_mp_h_yacht_coffee_table_01",
                      "apa_mp_h_yacht_coffee_table_02", "apa_mp_h_yacht_floor_lamp_01",
                      "imp_prop_impexp_half_cut_rack_01b", "apa_mp_h_yacht_side_table_01",
                      "apa_mp_h_yacht_side_table_02", "apa_mp_h_yacht_sofa_01", "apa_mp_h_yacht_sofa_02",
                      "apa_mp_h_yacht_stool_01", "apa_mp_h_yacht_strip_chair_01", "apa_mp_h_yacht_table_lamp_01",
                      "apa_mp_h_yacht_table_lamp_02", "apa_mp_h_yacht_table_lamp_03", "prop_flag_columbia",
                      "apa_mp_apa_yacht_o2_rail_a", "apa_mp_apa_yacht_o2_rail_b", "apa_mp_apa_yacht_o3_rail_a",
                      "apa_mp_apa_yacht_o3_rail_b", "proc_searock_01", "apa_mp_h_yacht_", "apa_mp_apa_yacht_option1",
                      "apa_mp_apa_yacht_option1_cola", "apa_mp_apa_yacht_option2", "apa_mp_apa_yacht_option2_cola",
                      "apa_mp_apa_yacht_option2_colb", "apa_mp_apa_yacht_option3", "apa_mp_apa_yacht_option3_cola",
                      "apa_mp_apa_yacht_option3_colb", "apa_mp_apa_yacht_option3_colc", "apa_mp_apa_yacht_option3_cold",
                      "apa_mp_apa_yacht_option3_cole", "apa_mp_apa_yacht_jacuzzi_cam",
                      "apa_mp_apa_yacht_jacuzzi_ripple003", "apa_mp_apa_yacht_jacuzzi_ripple1",
                      "apa_mp_apa_yacht_jacuzzi_ripple2", "apa_mp_apa_yacht_radar_01a", "apa_mp_apa_yacht_win",
                      "prop_crashed_heli", "prop_shamal_crash", "xm_prop_x17_shamal_crash", "apa_mp_apa_yacht_door",
                      "apa_mp_apa_yacht_door2", "apa_mp_apa_yacht", "prop_flagpole_2b", "prop_flagpole_2c",
                      "prop_flag_canada", "prop_flag_canada_s", "prop_flag_eu", "prop_beware_dog_sign",
                      "prop_flag_eu_s", "prop_target_blue_arrow", "prop_target_orange_arrow", "prop_target_purp_arrow",
                      "prop_target_red_arrow", "apa_prop_flag_argentina", "apa_prop_flag_australia",
                      "apa_prop_flag_austria", "apa_prop_flag_belgium", "apa_prop_flag_canadat_yt",
                      "apa_prop_flag_china", "apa_prop_flag_columbia", "apa_prop_flag_croatia",
                      "apa_prop_flag_czechrep", "apa_prop_flag_denmark", "apa_prop_flag_england", "apa_prop_flag_eu_yt",
                      "apa_prop_flag_finland", "apa_prop_flag_france", "apa_prop_flag_german_yt",
                      "apa_prop_flag_hungary", "apa_prop_flag_ireland", "apa_prop_flag_israel", "apa_prop_flag_italy",
                      "apa_prop_flag_jamaica", "apa_prop_flag_japan_yt", "apa_prop_flag_canada_yt",
                      "apa_prop_flag_lstein", "apa_prop_flag_malta", "apa_prop_flag_mexico_yt",
                      "apa_prop_flag_netherlands", "apa_prop_flag_newzealand", "apa_prop_flag_nigeria",
                      "apa_prop_flag_norway", "apa_prop_flag_palestine", "apa_prop_flag_poland",
                      "apa_prop_flag_portugal", "apa_prop_flag_puertorico", "apa_prop_flag_russia_yt",
                      "apa_prop_flag_scotland_yt", "apa_prop_flag_script", "apa_prop_flag_slovakia",
                      "apa_prop_flag_slovenia", "apa_prop_flag_southafrica", "apa_prop_flag_southkorea",
                      "apa_prop_flag_spain", "apa_prop_flag_sweden", "apa_prop_flag_switzerland",
                      "apa_prop_flag_turkey", "apa_prop_flag_uk_yt", "apa_prop_flag_us_yt", "apa_prop_flag_wales",
                      "prop_flag_uk", "prop_flag_uk_s", "prop_flag_us", "prop_flag_usboat", "prop_flag_us_r",
                      "prop_flag_us_s", "prop_flag_france", "prop_flag_france_s", "prop_flag_german",
                      "prop_flag_german_s", "prop_flag_ireland", "prop_flag_ireland_s", "prop_flag_japan",
                      "prop_flag_japan_s", "prop_flag_ls", "prop_flag_lsfd", "prop_flag_lsfd_s", "prop_flag_lsservices",
                      "prop_flag_lsservices_s", "prop_flag_ls_s", "prop_flag_mexico", "prop_flag_mexico_s",
                      "prop_flag_russia", "prop_flag_russia_s", "prop_flag_s", "prop_flag_sa", "prop_flag_sapd",
                      "prop_flag_sapd_s", "prop_flag_sa_s", "prop_flag_scotland", "prop_flag_scotland_s",
                      "prop_flag_sheriff", "prop_flag_sheriff_s", "prop_flamingo", "prop_swiss_ball_01",
                      "prop_air_bigradar", "prop_air_bigradar_l1", "prop_air_bigradar_l2", "prop_air_bigradar_slod",
                      "p_fib_rubble_s", "p_cs_mp_jet_01_s", "prop_poly_bag_money", "prop_air_radar_01",
                      "hei_prop_carrier_radar_1", "prop_carrier_radar_1_l1", "prop_asteroid_01", "prop_xmas_ext",
                      "prop_aircon_l_03", "prop_med_jet_01", "p_med_jet_01_s", "hei_prop_carrier_jet",
                      "hei_prop_heist_emp", "hei_prop_carrier_defense_01", "prop_aircon_m_04", "prop_mp_ramp_03",
                      "ch3_12_animplane1_lod", "ch3_12_animplane2_lod", "hei_prop_hei_pic_pb_plane", "light_plane_rig",
                      "prop_cs_plane_int_01", "prop_dummy_plane", "prop_mk_plane", "v_44_planeticket", "prop_planer_01",
                      "ch3_03_cliffrocks03b_lod", "ch3_04_rock_lod_02", "mp_player_introck", "Heist_Yacht",
                      "csx_coastsmalrock_05_", "mp_player_int_rock", "prop_flagpole_1a", "prop_flagpole_2a",
                      "prop_flagpole_3a", "prop_a4_pile_01", "cs2_10_sea_rocks_lod",
                      "cs2_11_sea_marina_xr_rocks_03_lod", "prop_gold_cont_01", "prop_hydro_platform",
                      "ch3_04_viewplatform_slod", "ch2_03c_rnchstones_lod", "proc_mntn_stone01", "proc_mntn_stone02",
                      "cs2_10_sea_shipwreck_lod", "des_shipsink_02", "prop_dock_shippad", "des_shipsink_03",
                      "des_shipsink_04", "prop_mk_flag", "prop_mk_flag_2", "proc_mntn_stone03",
                      "rsn_os_specialfloatymetal_n", "rsn_os_specialfloatymetal", "cs1_09_sea_ufo",
                      "rsn_os_specialfloaty2_light2", "rsn_os_specialfloaty2_light", "rsn_os_specialfloaty2",
                      "P_Spinning_Anus_S_Main", "P_Spinning_Anus_S_Root",
                      "cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a",
                      "sc1_04_rnmo_paintoverlaysc1_04_rnmo_paintoverlay_a", "rnbj_wallsigns_0001", "proc_sml_stones01",
                      "proc_sml_stones02", "proc_sml_stones03", "proc_stones_01", "proc_stones_02", "proc_stones_03",
                      "proc_stones_04", "proc_stones_05", "proc_stones_06", "prop_coral_stone_03",
                      "prop_coral_stone_04", "prop_gravestones_01a", "prop_gravestones_02a", "prop_gravestones_03a",
                      "prop_gravestones_04a", "prop_gravestones_05a", "prop_gravestones_06a", "prop_gravestones_07a",
                      "prop_gravestones_08a", "prop_gravestones_09a", "prop_gravestones_10a",
                      "prop_prlg_gravestone_05a_l1", "prop_prlg_gravestone_06a", "test_prop_gravestones_04a",
                      "test_prop_gravestones_05a", "test_prop_gravestones_07a", "test_prop_gravestones_08a",
                      "test_prop_gravestones_09a", "prop_prlg_gravestone_01a", "prop_prlg_gravestone_02a",
                      "prop_prlg_gravestone_03a", "prop_prlg_gravestone_04a", "prop_stoneshroom1", "prop_stoneshroom2",
                      "v_res_fa_stones01", "prop_rub_wheel_02", "dt1_lod_slod3", "cs4_lod_04_slod2", "po1_lod_slod4",
                      "id2_lod_slod4", "ap1_lod_slod4", "sm_lod_slod2_22", "prop_xmas_tree_int",
                      "test_prop_gravestones_01a", "test_prop_gravestones_02a", "prop_prlg_gravestone_05a",
                      "p_cablecar_s", "stt_prop_stunt_tube_l", "p_spinning_anus_s", "hei_prop_heist_tug",
                      "p_oil_slick_01", "prop_dummy_01", "p_tram_cash_s", "hw1_blimp_ce2", "hw1_blimp_ce2_lod",
                      "hw1_blimp_ce_lod", "hw1_blimp_cpr003", "hw1_blimp_cpr_null", "hw1_blimp_cpr_null2",
                      "prop_lev_des_barage_02", "prop_rope_hook_01", "prop_sub_crane_hook", "prop_vehicle_hook",
                      "prop_v_hook_s", "prop_dock_crane_02_hook", "prop_dock_crane_02_cab", "prop_winch_hook_long",
                      "prop_coathook_01", "prop_cs_sub_hook_01", "p_tram_crash_s", "p_ld_soc_ball_01", "p_parachute1_s",
                      "prop_lev_des_barge_01", "prop_lev_des_barge_02", "prop_sculpt_fix", "prop_winch_hook_short",
                      "prop_ld_hook", "prop_cable_hook_01", "des_tankercrash_01", "des_tankerexplosion_01",
                      "des_tankerexplosion_02", "des_trailerparka_02", "des_trailerparkb_02", "des_trailerparkc_02",
                      "des_trailerparkd_02", "des_traincrash_root2", "des_traincrash_root3", "des_traincrash_root4",
                      "des_traincrash_root5", "des_finale_vault_end", "des_finale_vault_root001",
                      "des_finale_vault_root002", "des_finale_vault_root003", "des_finale_vault_root004",
                      "des_finale_vault_start", "des_vaultdoor001_root001", "des_vaultdoor001_root002",
                      "des_vaultdoor001_root003", "des_vaultdoor001_root004", "des_vaultdoor001_root005",
                      "des_vaultdoor001_root006", "des_vaultdoor001_skin001", "des_vaultdoor001_start",
                      "des_traincrash_root6", "prop_ld_vault_door", "prop_vault_door_scene", "prop_vault_shutter",
                      "p_fin_vaultdoor_s", "prop_gold_vault_fence_l", "prop_gold_vault_fence_r",
                      "prop_gold_vault_gate_01", "prop_bank_vaultdoor", "des_traincrash_root7",
                      "ch2_03c_props_rrlwindmill_lod", "prop_yacht_lounger", "prop_yacht_seat_01", "prop_yacht_seat_02",
                      "prop_yacht_seat_03", "prop_test_rocks01", "prop_test_rocks02", "prop_test_rocks03",
                      "prop_test_rocks04", "marina_xr_rocks_02", "marina_xr_rocks_03", "marina_xr_rocks_04",
                      "marina_xr_rocks_05", "marina_xr_rocks_06", "prop_yacht_table_01", "csx_searocks_02",
                      "csx_searocks_03", "csx_searocks_04", "csx_searocks_05", "csx_searocks_06", "p_yacht_chair_01_s",
                      "p_yacht_sofa_01_s", "prop_yacht_table_02", "csx_coastboulder_00", "csx_coastboulder_01",
                      "csx_coastboulder_02", "csx_coastboulder_03", "csx_coastboulder_04", "csx_coastboulder_05",
                      "csx_coastboulder_06", "csx_coastboulder_07", "csx_coastrok1", "csx_coastrok2", "csx_coastrok3",
                      "csx_coastrok4", "csx_coastsmalrock_01", "csx_coastsmalrock_02", "csx_coastsmalrock_03",
                      "csx_coastsmalrock_04", "csx_coastsmalrock_05", "prop_yacht_table_03", "bkr_prop_biker_tube_crn",
                      "bkr_prop_biker_tube_crn2", "bkr_prop_biker_tube_cross", "bkr_prop_biker_tube_gap_01",
                      "bkr_prop_biker_tube_gap_02", "bkr_prop_biker_tube_gap_03", "bkr_prop_biker_tube_l",
                      "bkr_prop_biker_tube_m", "bkr_prop_biker_tube_s", "bkr_prop_biker_tube_xs",
                      "bkr_prop_biker_tube_xxs", "bkr_prop_biker_bblock_cor", "bkr_prop_biker_bblock_cor_02",
                      "bkr_prop_biker_bblock_cor_03", "bkr_prop_biker_bblock_huge_01", "bkr_prop_biker_bblock_hump_02",
                      "bkr_prop_biker_bblock_hump_03", "bkr_prop_biker_bblock_huge_02", "bkr_prop_biker_bblock_huge_03",
                      "bkr_prop_biker_bblock_huge_04", "bkr_prop_biker_bblock_huge_05", "bkr_prop_biker_bblock_lrg1",
                      "bkr_prop_biker_bblock_lrg2", "bkr_prop_biker_bblock_lrg3", "bkr_prop_biker_bblock_mdm1",
                      "bkr_prop_biker_bblock_mdm2", "bkr_prop_biker_bblock_mdm3", "bkr_prop_biker_bblock_qp",
                      "bkr_prop_biker_bblock_qp2", "bkr_prop_biker_bblock_qp3", "bkr_prop_biker_bblock_sml1",
                      "bkr_prop_biker_bblock_sml2", "bkr_prop_biker_bblock_sml3", "bkr_prop_biker_bblock_xl1",
                      "bkr_prop_biker_bblock_xl2", "bkr_prop_biker_bblock_xl3", "bkr_prop_biker_bowlpin_stand",
                      "bkr_prop_biker_target", "bkr_prop_biker_target_small", "stt_prop_ramp_adj_flip_m",
                      "stt_prop_ramp_adj_flip_mb", "stt_prop_ramp_adj_flip_s", "stt_prop_ramp_adj_flip_sb",
                      "stt_prop_ramp_adj_hloop", "stt_prop_ramp_adj_loop", "stt_prop_ramp_jump_l",
                      "stt_prop_ramp_jump_m", "stt_prop_ramp_jump_s", "stt_prop_ramp_jump_xl", "stt_prop_ramp_jump_xs",
                      "stt_prop_ramp_jump_xxl", "stt_prop_ramp_multi_loop_rb", "stt_prop_ramp_spiral_l",
                      "stt_prop_ramp_spiral_l_l", "stt_prop_ramp_spiral_l_m", "stt_prop_ramp_spiral_l_s",
                      "stt_prop_ramp_spiral_l_xxl", "stt_prop_ramp_spiral_m", "stt_prop_ramp_spiral_s",
                      "stt_prop_ramp_spiral_xxl", "stt_prop_stunt_bblock_huge_01", "stt_prop_stunt_bblock_huge_02",
                      "stt_prop_stunt_bblock_huge_03", "stt_prop_stunt_bblock_huge_04", "stt_prop_stunt_bblock_huge_05",
                      "stt_prop_stunt_bblock_hump_01", "stt_prop_stunt_bblock_hump_02", "stt_prop_stunt_bblock_lrg1",
                      "stt_prop_stunt_bblock_lrg2", "stt_prop_stunt_bblock_lrg3", "stt_prop_stunt_bblock_mdm1",
                      "stt_prop_stunt_bblock_mdm2", "stt_prop_stunt_bblock_mdm3", "stt_prop_stunt_bblock_qp",
                      "stt_prop_stunt_bblock_qp2", "stt_prop_stunt_bblock_qp3", "stt_prop_stunt_bblock_sml1",
                      "stt_prop_stunt_bblock_sml2", "stt_prop_stunt_bblock_sml3", "stt_prop_stunt_bblock_xl1",
                      "stt_prop_stunt_bblock_xl2", "stt_prop_stunt_bblock_xl3", "stt_prop_stunt_bowlpin_stand",
                      "sr_prop_spec_tube_04a", "sr_prop_spec_tube_crn_01a", "sr_prop_spec_tube_crn_02a",
                      "sr_prop_spec_tube_crn_03a", "sr_prop_spec_tube_crn_04a", "sr_prop_spec_tube_crn_05a",
                      "sr_prop_spec_tube_crn_30d_01a", "sr_prop_spec_tube_crn_30d_02a", "sr_prop_spec_tube_crn_30d_03a",
                      "sr_prop_spec_tube_crn_30d_04a", "sr_prop_spec_tube_crn_30d_05a", "sr_prop_spec_tube_l_01a",
                      "sr_prop_spec_tube_l_02a", "sr_prop_spec_tube_l_03a", "sr_prop_spec_tube_l_04a",
                      "sr_prop_spec_tube_l_05a", "sr_prop_spec_tube_m_01a", "sr_prop_spec_tube_m_02a",
                      "sr_prop_spec_tube_m_03a", "sr_prop_spec_tube_m_04a", "sr_prop_spec_tube_m_05a",
                      "sr_prop_spec_tube_refill", "sr_prop_spec_tube_s_01a", "sr_prop_spec_tube_s_02a",
                      "sr_prop_spec_tube_s_03a", "sr_prop_spec_tube_s_04a", "sr_prop_spec_tube_s_05a",
                      "sr_prop_spec_tube_xxs_01a", "sr_prop_spec_tube_xxs_02a", "sr_prop_spec_tube_xxs_03a",
                      "sr_prop_spec_tube_xxs_04a", "sr_prop_spec_tube_xxs_05a", "sr_prop_special_bblock_lrg11",
                      "sr_prop_special_bblock_lrg2", "sr_prop_special_bblock_lrg3", "sr_prop_special_bblock_mdm1",
                      "sr_prop_special_bblock_mdm2", "sr_prop_special_bblock_mdm3", "sr_prop_special_bblock_sml1",
                      "sr_prop_special_bblock_sml2", "sr_prop_special_bblock_sml3", "sr_prop_special_bblock_xl1",
                      "sr_prop_special_bblock_xl3", "sr_prop_special_bblock_xl3_fixed", "sr_prop_sr_track_wall",
                      "sr_prop_sr_tube_end", "sr_prop_sr_tube_wall", "sr_prop_stunt_tube_crn2_01a",
                      "sr_prop_stunt_tube_crn2_02a", "sr_prop_stunt_tube_crn2_03a", "sr_prop_stunt_tube_crn2_04a",
                      "sr_prop_stunt_tube_crn2_05a", "sr_prop_stunt_tube_crn_15d_01a", "sr_prop_stunt_tube_crn_15d_02a",
                      "sr_prop_stunt_tube_crn_15d_03a", "sr_prop_stunt_tube_crn_15d_04a",
                      "sr_prop_stunt_tube_crn_15d_05a", "sr_prop_stunt_tube_crn_5d_01a",
                      "sr_prop_stunt_tube_crn_5d_02a", "sr_prop_stunt_tube_crn_5d_03a", "sr_prop_stunt_tube_crn_5d_04a",
                      "sr_prop_stunt_tube_crn_5d_05a", "sr_prop_stunt_tube_xs_01a", "sr_prop_stunt_tube_xs_02a",
                      "sr_prop_stunt_tube_xs_03a", "sr_prop_stunt_tube_xs_04a", "sr_prop_stunt_tube_xs_05a",
                      "sr_prop_track_straight_l_d15", "sr_prop_track_straight_l_d30", "sr_prop_track_straight_l_d45",
                      "sr_prop_track_straight_l_d5", "sr_prop_track_straight_l_u15", "prop_knife",
                      "sr_prop_track_straight_l_u30", "sr_prop_track_straight_l_u45", "sr_prop_track_straight_l_u5",
                      "stt_prop_race_start_line_01", "stt_prop_race_start_line_01b", "stt_prop_race_start_line_02",
                      "stt_prop_race_start_line_02b", "stt_prop_race_start_line_03", "stt_prop_race_start_line_03b",
                      "stt_prop_stunt_domino", "stt_prop_stunt_jump15", "stt_prop_stunt_jump30",
                      "stt_prop_stunt_jump45", "stt_prop_stunt_jump_l", "stt_prop_stunt_jump_lb",
                      "stt_prop_stunt_jump_loop", "stt_prop_stunt_jump_m", "stt_prop_stunt_jump_mb",
                      "stt_prop_stunt_jump_s", "stt_prop_stunt_jump_sb", "stt_prop_stunt_landing_zone_01",
                      "stt_prop_stunt_ramp", "stt_prop_stunt_soccer_ball", "stt_prop_stunt_soccer_goal",
                      "stt_prop_stunt_soccer_lball", "stt_prop_stunt_soccer_sball", "stt_prop_stunt_target",
                      "stt_prop_stunt_target_small", "stt_prop_stunt_track_bumps", "stt_prop_stunt_track_cutout",
                      "stt_prop_stunt_track_dwlink", "stt_prop_stunt_track_dwlink_02", "stt_prop_stunt_track_dwsh15",
                      "stt_prop_stunt_track_dwshort", "stt_prop_stunt_track_dwslope15",
                      "stt_prop_stunt_track_dwslope30", "stt_prop_stunt_track_dwslope45", "stt_prop_stunt_track_dwturn",
                      "stt_prop_stunt_track_dwuturn", "stt_prop_stunt_track_exshort", "stt_prop_stunt_track_fork",
                      "stt_prop_stunt_track_funlng", "stt_prop_stunt_track_funnel", "stt_prop_stunt_track_hill",
                      "stt_prop_stunt_track_hill2", "stt_prop_stunt_track_jump", "stt_prop_stunt_track_link",
                      "stt_prop_stunt_track_otake", "stt_prop_stunt_track_sh15", "stt_prop_stunt_track_sh30",
                      "stt_prop_stunt_track_sh45", "stt_prop_stunt_track_sh45_a", "stt_prop_stunt_track_short",
                      "stt_prop_stunt_track_slope15", "stt_prop_stunt_track_slope30", "stt_prop_stunt_track_slope45",
                      "stt_prop_stunt_track_start", "ar_prop_ar_stunt_block_01a", "ar_prop_ar_stunt_block_01b",
                      "xs_prop_hamburgher_wl", "prop_fnclink_05crnr1", "prop_container_01a", "prop_contnr_pile_01a",
                      "ce_xr_ctr2", "prop_parking_hut_2", "csx_seabed_rock3_", "db_apart_03_", "db_apart_09_",
                      "v_ilev_gc_weapons", "xs_prop_plastic_bottle_wl", "prop_box_wood06a", "p_ferris_wheel_amo_l2",
                      "prop_bumper_car_01", "bkr_prop_bkr_cashpile_04", "prop_fnclink_03a", "apa_mp_h_acc_rugwoolm_03",
                      "prop_container_ld2", "prop_container_05a", "stt_prop_stunt_bowling_ball", "prop_cons_ply02",
                      "prop_conslift_rail", "prop_front_seat_02", "prop_rub_buswreck_06", "prop_distantcar_truck",
                      "prop_dock_crane_01", "prop_fan_palm_01a", "prop_facgate_05_r", "prop_bmu_01",
                      "prop_billboard_09", "prop_warehseshelf02", "prop_watertower03", "prop_weeds_nxg05b",
                      "prop_skip_02a", "hei_heist_bed_double_08", "gr_prop_gr_target_small_04a",
                      "gr_prop_gr_tool_draw_01d", "gr_prop_gr_crates_rifles_02a", "ch3_01_dino", "p_pallet_02a_s",
                      "prop_conc_blocks01a", "prop_consign_01a", "prop_byard_net02", "prop_mb_cargo_04b",
                      "prop_mb_crate_01a_set", "prop_pipe_stack_01", "prop_roadcone01c", "prop_rub_cage01b",
                      "prop_sign_road_01a", "prop_sign_road_03m", "prop_traffic_rail_2", "prop_traffic_rail_1a",
                      "prop_traffic_03a", "prop_traffic_01d", "prop_skid_trolley_1", "hei_prop_yah_seat_03",
                      "hei_prop_yah_table_03", "lts_prop_lts_elecbox_24", "lts_prop_lts_elecbox_24b",
                      "p_airdancer_01_s", "p_dumpster_t", "p_ld_coffee_vend_01", "p_patio_lounger1_s",
                      "prop_air_bagloader2_cr", "prop_air_blastfence_01", "prop_air_stair_01", "prop_air_sechut_01",
                      "prop_airport_sale_sign", "xm_prop_x17_silo_open_01a", "xm_prop_x17_silo_door_l_01a",
                      "stt_prop_wallride_01", "stt_prop_wallride_01b", "stt_prop_wallride_02", "stt_prop_wallride_02b",
                      "stt_prop_wallride_04", "stt_prop_wallride_05", "stt_prop_wallride_05b", "stt_prop_wallride_45l",
                      "stt_prop_wallride_45la", "stt_prop_wallride_45r", "stt_prop_wallride_45ra",
                      "stt_prop_wallride_90l", "stt_prop_wallride_90lb", "stt_prop_wallride_90r",
                      "stt_prop_wallride_90rb", "stt_prop_track_bend2_bar_l_b", "stt_prop_track_bend2_l",
                      "stt_prop_track_bend2_l_b", "stt_prop_track_bend_15d", "stt_prop_track_bend_15d_bar",
                      "stt_prop_track_bend_180d", "stt_prop_track_bend_180d_bar", "stt_prop_track_bend_30d",
                      "stt_prop_track_bend_30d_bar", "stt_prop_track_bend_5d", "stt_prop_track_bend_5d_bar",
                      "stt_prop_track_bend_bar_l", "stt_prop_track_bend_bar_l_b", "stt_prop_track_bend_bar_m",
                      "stt_prop_track_bend_l", "stt_prop_track_bend_l_b", "stt_prop_track_bend_m",
                      "stt_prop_track_bend_l", "stt_prop_track_bend_l_b", "stt_prop_track_bend_m",
                      "stt_prop_track_block_01", "stt_prop_track_block_02", "stt_prop_track_block_03",
                      "stt_prop_track_chicane_l", "stt_prop_track_chicane_r", "stt_prop_track_chicane_l_02",
                      "stt_prop_track_chicane_r_02", "stt_prop_track_cross", "stt_prop_track_cross_bar",
                      "stt_prop_track_fork_bar", "stt_prop_track_funnel", "stt_prop_track_funnel_ads_01a",
                      "stt_prop_track_funnel_ads_01b", "stt_prop_track_funnel_ads_01c", "stt_prop_track_jump_01a",
                      "stt_prop_track_jump_01b", "stt_prop_track_jump_01c", "stt_prop_track_jump_02a",
                      "stt_prop_track_jump_02b", "stt_prop_track_jump_02c", "stt_prop_track_link",
                      "stt_prop_track_slowdown", "stt_prop_track_slowdown_t1", "stt_prop_track_slowdown_t2",
                      "stt_prop_track_speedup", "stt_prop_track_speedup_t1", "stt_prop_track_speedup_t2",
                      "stt_prop_track_start", "stt_prop_track_start_02", "stt_prop_track_straight_bar_m",
                      "stt_prop_track_straight_bar_l", "stt_prop_track_straight_bar_s", "stt_prop_track_straight_l",
                      "stt_prop_track_straight_lm", "stt_prop_track_straight_lm_bar", "stt_prop_track_straight_m",
                      "stt_prop_track_straight_s", "stt_prop_track_tube_01", "stt_prop_track_tube_02",
                      "stt_prop_tyre_wall_01", "stt_prop_stunt_tube_jmp", "stt_prop_stunt_tube_jmp2",
                      "stt_prop_stunt_tube_m", "stt_prop_stunt_tube_qg", "stt_prop_stunt_tube_s",
                      "stt_prop_stunt_tube_speed", "stt_prop_stunt_tube_speeda", "stt_prop_stunt_tube_speedb",
                      "stt_prop_stunt_tube_xs", "stt_prop_stunt_tube_xxs", "stt_prop_stunt_wideramp", "prop_beach_fire",
                      "prop_fire_exting_1a", "prop_fire_exting_1b", "prop_fire_exting_2a", "prop_fire_exting_3a",
                      "prop_gas_tank_01a", "prop_gascyl_01a", "prop_cs_dildo_01", "prop_ld_toilet_01",
                      "prop_ld_bomb_anim", "p_bloodsplat_s", "prop_cs_dog_lead_2a", "prop_ld_farm_couch01",
                      "p_crahsed_heli_s", "prop_rock_4_big2", "prop_beachflag_le", "prop_gold_cont_01",
                      "apa_mp_apa_yacht", "prop_gascage01", "prop_ld_ferris_wheel", "apa_mp_apa_crashed_usaf_01a",
                      "apa_prop_ss1_mpint_garage2", "bkr_prop_biker_garage_locker_01", "bkr_prop_bkr_cashpile_01",
                      "bkr_prop_weed_med_01b", "gr_prop_gr_doorpart_f", "gr_prop_gr_crates_weapon_mix_01b",
                      "gr_prop_gr_fnclink_03g", "gr_prop_gr_fnclink_03f", "gr_prop_gr_para_s_01", "prop_dt1_20_mp_gar",
                      "prop_elecbox_01a", "prop_elecbox_16", "prop_phonebox_04", "prop_pier_kiosk_03",
                      "prop_pile_dirt_02", "prop_pile_dirt_07_cr", "prop_rub_wreckage_9", "prop_telegraph_01b",
                      "prop_ind_barge_01_cr", "prop_ind_deiseltank", "prop_ind_oldcrane", "prop_inflatearch_01",
                      "xm_prop_tunnel_fan_01", "xm_prop_x17_l_glass_01", "xm_prop_x17_mine_01a", "xm_prop_x17_mine_03a",
                      "xm_prop_x17_osphatch_27m", "xm_prop_x17_pillar", "xm_prop_x17_osphatch_op_27m",
                      "xm_prop_x17_silo_01a", "xm_prop_x17_sub", "xm_prop_x17_sub_damage", "xm_prop_x17_trail_01a",
                      "xm_prop_x17_xmas_tree_int", "prop_alien_egg_01", "prop_windmill_01",
                      "stt_prop_hoop_constraction_01a", "stt_prop_hoop_small_01", "stt_prop_hoop_tyre_01a",
                      "stt_prop_stunt_bowling_pin", "stt_prop_stunt_track_st_01", "stt_prop_stunt_track_turnice",
                      "stt_prop_stunt_track_uturn", "stt_prop_stunt_tube_crn", "stt_prop_stunt_tube_crn2",
                      "stt_prop_stunt_tube_crn_15d", "stt_prop_stunt_tube_crn_30d", "stt_prop_stunt_tube_crn_5d",
                      "stt_prop_stunt_tube_cross", "stt_prop_stunt_tube_end", "stt_prop_stunt_tube_ent",
                      "stt_prop_stunt_tube_fn_01", "stt_prop_stunt_tube_fn_02", "stt_prop_stunt_tube_fn_03",
                      "stt_prop_stunt_tube_fn_04", "stt_prop_stunt_tube_fn_05", "stt_prop_stunt_tube_fork",
                      "stt_prop_stunt_tube_gap_01", "stt_prop_stunt_tube_gap_02", "stt_prop_stunt_tube_gap_03",
                      "stt_prop_stunt_tube_hg", "apa_mp_apa_y1_l1a", "apa_mp_apa_y1_l1b", "apa_mp_apa_y1_l1c",
                      "apa_mp_apa_y1_l1d", "apa_mp_apa_y1_l2a", "apa_mp_apa_y1_l2b", "apa_mp_apa_y1_l2c",
                      "apa_mp_apa_y1_l2d", "apa_mp_apa_y2_l1a", "apa_mp_apa_y2_l1b", "apa_mp_apa_y2_l1c",
                      "apa_mp_apa_y2_l1d", "apa_mp_apa_y2_l2a", "apa_mp_apa_y2_l2b", "apa_mp_apa_y2_l2c",
                      "apa_mp_apa_y2_l2d", "apa_mp_apa_y3_l1a", "apa_mp_apa_y3_l1b", "apa_mp_apa_y3_l1c",
                      "apa_mp_apa_y3_l1d", "apa_mp_apa_y3_l2a", "apa_mp_apa_y3_l2b", "apa_mp_apa_y3_l2c",
                      "apa_mp_apa_y3_l2d", "hei_prop_carrier_cargo_02a", "p_ferris_car_01", "prop_cj_big_boat",
                      "prop_steps_big_01", "v_ilev_lest_bigscreen", "prop_carcreeper", "apa_mp_h_bed_double_09",
                      "apa_mp_h_bed_double_08", "apa_mp_h_bed_wide_05", "prop_cattlecrush", "prop_cs_documents_01",
                      "prop_construcionlamp_01", "prop_ferris_car_01_lod1", "prop_fncconstruc_01d",
                      "prop_fncconstruc_02a", "p_dock_crane_cabl_s", "prop_dock_crane_lift", "prop_dock_float_1",
                      "csx_seabed_bldr4_", "imp_prop_impexp_sofabed_01a", "02gate3_l", "ar_prop_ar_neon_gate4x_02a",
                      "xs_propintarena_structure_f_01a", "xs_propintarena_structure_f_02a",
                      "xs_propintarena_structure_f_02b", "xs_propintarena_structure_f_02c",
                      "xs_propintarena_structure_f_02d", "xs_propintarena_structure_f_02e",
                      "xs_propintarena_structure_f_03a", "xs_propintarena_structure_f_03b",
                      "xs_propintarena_structure_f_03c", "xs_propintarena_structure_f_03d",
                      "xs_propintarena_structure_f_03e", "xs_propintarena_structure_f_04a", "prop_hand_toilet",
                      "ar_prop_ar_neon_gate_01a", "ar_prop_ar_neon_gate_01b", "ar_prop_ar_neon_gate_02a",
                      "ar_prop_ar_neon_gate_02b", "ar_prop_ar_neon_gate_03a", "des_frenchdoors_end",
                      "p_parachute_fallen_s", "xs_combined2_dystplane_10"}

Whitelist["Props"] = {"prop_ballistic_shield", "prop_amb_phone", "xm_prop_x17_tem_control_01", "player_zero",
                      "prop_bowling_ball", "p_parachute1_mp_s", "prop_poly_bag_money", "p_amb_clipboard_01",
                      "hei_prop_hei_cash_trolly_01", "prop_choc_meto", "prop_ld_flow_bottle", "prop_amb_donut",
                      "v_res_tt_pizzaplate", "prop_mp_cone_02", "prop_energy_drink", "prop_fib_coffee",
                      "ng_proc_sodacan_01b", "prop_whiskey_bottle", "prop_tequila_bottle", "prop_vodka_bottle",
                      "ba_prop_club_water_bottle", "p_ing_coffeecup_01", "v_res_tt_can03", "ng_proc_sodacan_01a",
                      "prop_amb_beer_bottle", "prop_beer_logopen", "p_whiskey_notop", "ng_proc_food_chips01b",
                      "prop_food_bs_chips", "prop_food_cb_nugets", "prop_wine_bot_01", "prop_wine_bot_02",
                      "prop_wine_rose", "prop_wine_white", "prop_choc_pq", "prop_taco_01", "v_ret_ta_firstaid",
                      "prop_cs_pills", "prop_boombox_01", "prop_ld_case_01", "prop_ld_case_01_s",
                      "prop_security_case_01", "w_am_case", "prop_ld_suitcase_01", "xm_prop_x17_bag_med_01a",
                      "prop_tool_box_04", "prop_cs_rub_binbag_01", "prop_microphone_02", "p_ing_microphonel_01",
                      "prop_v_bmike_01", "prop_parking_wand_01", "prop_beggers_sign_01", "prop_beggers_sign_03",
                      "prop_beggers_sign_04", "prop_cs_hand_radio", "prop_fib_coffee", "prop_fib_coffee",
                      "hei_prop_heist_box", "p_amb_brolly_01", "p_amb_brolly_01_s", "prop_cs_burger_01",
                      "prop_cs_hotdog_01", "prop_amb_donut", "p_cs_bottle_01", "prop_energy_drink",
                      "prop_amb_beer_bottle", "p_whiskey_notop", "prop_beer_logopen", "prop_beer_blr",
                      "prop_ld_flow_bottle", "prop_gascyl_01a", "prop_tool_broom", "prop_el_guitar_01",
                      "prop_el_guitar_02", "prop_el_guitar_03", "prop_acc_guitar_01", "prop_pap_camera_01",
                      "prop_v_cam_01", "p_amb_clipboard_01", "prop_tourist_map_01", "prop_notepad_01",
                      "prop_police_phone", "prop_cs_ciggy_01", "prop_curl_bar_01", "prop_tool_hammer",
                      "prop_fishing_rod_01", "prop_leaf_blower_01", "prop_rag_01", "prop_novel_01",
                      "v_ilev_mr_rasberryclean", "prop_anim_cash_pile_01", "imp_prop_impexp_front_bumper_02a",
                      "prop_car_door_01", "prop_car_door_02", "prop_car_door_03", "prop_car_door_04", "prop_car_seat",
                      "prop_wheel_tyre", "prop_wheel_03", "prop_car_battery_01", "prop_car_engine_01", "prop_bong_01",
                      "prop_dumpster_02a", "prop_ld_flow_bottle", "prop_toolchest_01", "p_ld_stinger_s",
                      "prop_cs_cardbox_01", "p_amb_coffeecup_01", "ba_prop_battle_champ_open", "prop_fire_exting_1a",
                      "prop_amb_phone", "hei_prop_yah_glass_01", "hei_prop_yah_glass_02", "hei_prop_yah_glass_03",
                      "hei_prop_yah_glass_04", "hei_prop_yah_glass_05", "hei_prop_yah_glass_06",
                      "hei_prop_yah_glass_07", "hei_prop_yah_glass_08", "hei_prop_yah_glass_09",
                      "hei_prop_yah_glass_10", "prop_cs_walkie_talkie", "w_am_baseball", "w_am_brfcase", "w_am_case",
                      "w_am_digiscanner", "w_am_fire_exting", "w_am_flare", "w_am_jerrycan", "w_ar_advancedrifle",
                      "w_ar_advancedrifle_mag1", "w_ar_advancedrifle_mag2", "w_ar_assaultrifle",
                      "w_ar_assaultrifle_mag1", "w_ar_assaultrifle_mag2", "w_ar_bullpuprifle", "w_ar_bullpuprifle_mag1",
                      "w_ar_bullpuprifle_mag2", "w_ar_carbinerifle", "w_ar_carbinerifle_mag1", "w_ar_carbinerifle_mag2",
                      "w_ar_musket", "w_ar_railgun", "w_ar_railgun_mag1", "w_ar_specialcarbine",
                      "w_ar_specialcarbine_mag1", "w_ar_specialcarbine_mag2", "w_at_ar_afgrip", "w_at_ar_flsh",
                      "w_at_ar_supp", "w_at_ar_supp_02", "w_at_pi_flsh", "w_at_pi_supp", "w_at_pi_supp_2",
                      "w_at_railcover_01", "w_at_scope_large", "w_at_scope_macro", "w_at_scope_macro_2",
                      "w_at_scope_max", "w_at_scope_medium", "w_at_scope_small", "w_at_scope_small_2", "w_at_sr_supp",
                      "w_at_sr_supp_2", "w_ex_apmine", "w_ex_birdshat", "w_ex_grenadefrag", "w_ex_grenadesmoke",
                      "w_ex_molotov", "w_ex_pe", "w_ex_snowball", "w_lr_40mm", "w_lr_firework", "w_lr_firework_rocket",
                      "w_lr_grenadelauncher", "w_lr_homing", "w_lr_homing_rocket", "w_lr_rpg", "w_lr_rpg_rocket",
                      "w_me_bat", "w_me_bottle", "w_me_crowbar", "w_me_dagger", "w_me_gclub", "w_me_hammer",
                      "w_me_hatchet", "w_me_knife_01", "w_me_nightstick", "w_mg_combatmg", "w_mg_combatmg_mag1",
                      "w_mg_combatmg_mag2", "w_mg_mg", "w_mg_mg_mag1", "w_mg_mg_mag2", "w_mg_minigun", "w_pi_appistol",
                      "w_pi_appistol_mag1", "w_pi_appistol_mag2", "w_pi_combatpistol", "w_pi_combatpistol_mag1",
                      "w_pi_combatpistol_mag2", "w_pi_flaregun", "w_pi_flaregun_mag1", "w_pi_flaregun_shell",
                      "w_pi_heavypistol", "w_pi_heavypistol_mag1", "w_pi_heavypistol_mag2", "w_pi_pistol",
                      "w_pi_pistol50", "w_pi_pistol50_mag1", "w_pi_pistol50_mag2", "w_pi_pistol_mag1",
                      "w_pi_pistol_mag2", "w_pi_pistolmk2", "w_pi_sns_pistol", "w_pi_sns_pistol_mag1",
                      "w_pi_sns_pistol_mag2", "w_pi_stungun", "w_pi_vintage_pistol", "w_pi_vintage_pistol_mag1",
                      "w_pi_vintage_pistol_mag2", "w_sb_assaultsmg", "w_sb_assaultsmg_mag1", "w_sb_assaultsmg_mag2",
                      "w_sb_gusenberg", "w_sb_gusenberg_mag1", "w_sb_gusenberg_mag2", "w_sb_microsmg",
                      "w_sb_microsmg_mag1", "w_sb_microsmg_mag2", "w_sb_smg", "w_sb_smg_mag1", "w_sb_smg_mag2",
                      "w_sg_assaultshotgun", "w_sg_assaultshotgun_mag1", "w_sg_assaultshotgun_mag2",
                      "w_sg_bullpupshotgun", "w_sg_heavyshotgun", "w_sg_heavyshotgun_mag1", "w_sg_heavyshotgun_mag2",
                      "w_sg_pumpshotgun", "w_sg_sawnoff", "w_sr_heavysniper", "w_sr_heavysniper_mag1",
                      "w_sr_marksmanrifle", "w_sr_marksmanrifle_mag1", "w_sr_marksmanrifle_mag2", "w_sr_sniperrifle",
                      "w_sr_sniperrifle_mag1", "prop_cs_credit_card", "bkr_prop_weed_01_small_01c",
                      "bkr_prop_weed_01_small_01b", "bkr_prop_weed_01_small_01a", "bkr_prop_weed_med_01a",
                      "bkr_prop_weed_med_01b", "bkr_prop_weed_lrg_01a", "bkr_prop_weed_lrg_01b",
                      "bkr_prop_coke_bakingsoda_o", "bkr_prop_coke_fullscoop_01a", "bkr_prop_coke_doll",
                      "bkr_prop_coke_boxedDoll", "bkr_prop_coke_dollCast", "bkr_prop_coke_dollmould",
                      "bkr_prop_coke_fullmetalbowl_02", "bkr_prop_coke_press_01b", "bkr_prop_coke_dollboxfolded",
                      "bkr_prop_meth_ammonia", "bkr_prop_fakeid_clipboard_01a", "bkr_prop_fakeid_penclipboard",
                      "bkr_prop_meth_sacid", "bkr_prop_meth_bigbag_04a", "bkr_prop_meth_bigbag_03a",
                      "bkr_prop_meth_openbag_02", "bkr_prop_coke_scale_01", "bkr_prop_meth_scoop_01a",
                      "bkr_prop_weed_dry_01a", "bkr_prop_weed_leaf_01a", "bkr_prop_weed_bag_01a",
                      "bkr_prop_weed_bud_02b", "bkr_prop_weed_bud_02a", "bkr_prop_weed_bag_pile_01a",
                      "bkr_prop_weed_bucket_open_01a", "bkr_prop_coke_tin_01", "bkr_prop_tin_cash_01a",
                      "bkr_prop_money_unsorted_01", "bkr_prop_money_wrapped_01", "bkr_prop_fakeid_papercutter",
                      "bkr_prop_cutter_moneypage", "bkr_prop_fakeid_table", "bkr_prop_cutter_moneystack_01a",
                      "bkr_prop_cutter_moneystrip", "bkr_prop_cutter_singlestack_01a", "bkr_prop_money_pokerbucket",
                      "ng_proc_cigar01a", "ng_proc_cigarette01a", "ng_proc_cigbuts01a", "ng_proc_cigbuts02a",
                      "ng_proc_cigbuts03a", "ng_proc_coffee_01a", "ng_proc_food_chips01a", "ng_proc_food_chips01b",
                      "ng_proc_food_chips01c", "ng_proc_food_nana1a", "ng_proc_litter_plasbot2", "ng_proc_sodabot_01a",
                      "ng_proc_sodacan_01a", "ng_proc_sodacan_01b", "ng_proc_sodacup_01a", "ng_proc_sodacup_01b",
                      "ng_proc_temp", "ba_prop_battle_glowstick_01", "ba_prop_battle_hobby_horse", "p_amb_brolly_01",
                      "prop_notepad_01", "prop_pencil_01", "hei_prop_heist_box", "prop_single_rose", "prop_cs_ciggy_01",
                      "hei_heist_sh_bong_01", "prop_ld_suitcase_01", "prop_security_case_01", "prop_police_id_board",
                      "prop_drink_whisky", "prop_amb_beer_bottle", "prop_plastic_cup_02", "prop_amb_donut",
                      "prop_cs_burger_01", "prop_sandwich_01", "prop_ecola_can", "prop_choc_ego", "prop_drink_redwine",
                      "prop_champ_flute", "prop_drink_champ", "prop_cigar_02", "prop_cigar_01", "prop_acc_guitar_01",
                      "prop_el_guitar_01", "prop_el_guitar_03", "prop_novel_01", "prop_snow_flower_02",
                      "v_ilev_mr_rasberryclean", "p_michael_backpack_s", "p_amb_clipboard_01", "prop_tourist_map_01",
                      "prop_beggers_sign_03", "prop_anim_cash_pile_01", "prop_pap_camera_01", "p_cs_joint_02",
                      "prop_amb_ciggy_01", "prop_ld_case_01", "prop_cs_tablet", "prop_npc_phone", "prop_npc_phone_02",
                      "prop_sponge_01", "prop_energy_drink", "prop_roadcone01a", "prop_roadcone01b", "prop_roadcone01c",
                      "prop_roadcone02a", "prop_roadcone02b", "prop_roadcone02c", "prop_tool_pickaxe", "L1_1",
                      "prop_cs_fuel_nozle", "prop_rub_table_02", "p_car_keys_01", "p_cs_clipboard", "diables_x_quasar_phone_grey", 
                      "diables_x_quasar_phone_black", "diables_x_quasar_phone_blue", "diables_x_quasar_phone_gold", "diables_x_quasar_phone_purple", 
                      "diables_x_quasar_phone_red", "diables_x_quasar_phone_green", "diables_x_quasar_phone_greenlight", "diables_x_quasar_phone_pink",
                      "diables_x_quasar_phone_white","prop_ld_binbag_01","prop_jpolice_shield","prop_jsheriff_shield","prop_jswat_shield",
                      "prop_jfib_shield","prop_jnoose_shield","prop_jswat_shield"}
