Blacklist["Weapons"] = {'WEAPON_RPG', 'WEAPON_GRENADELAUNCHER', 'WEAPON_GRENADELAUCHER_SMOKE', 'WEAPON_MINIGUN',
                        'WEAPON_RAILGUN', 'WEAPON_HOMINGLAUNCHER', 'WEAPON_RAYMINIGUN', 'WEAPON_EMPLAUNCHER',
                        'WEAPON_HOMINGLAUNCHER', 'WEAPON_GRENADE', 'WEAPON_MOLOTOV',
                        'WEAPON_HOMINGLAUNCHER', 'WEAPON_STICKYBOMB', 'WEAPON_PROXMINE', 'WEAPON_PIPEBOMB',
                        'WEAPON_FLARE', 'WEAPON_COMPACTLAUNCHER', 'weapon_dagger', 'weapon_battleaxe', 'weapon_bottle',
                        'weapon_crowbar', 'weapon_golfclub', 'weapon_hammer', 'weapon_knife', 'weapon_machete',
                        'weapon_wrench', 'weapon_stone_hatchet', 'weapon_appistol', 'weapon_ceramicpistol',
                        'weapon_flaregun', 'weapon_gadgetpistol', 'weapon_heavypistol', 'weapon_revolver',
                        'weapon_revolver_mk2', 'weapon_marksmanpistol', 'weapon_navyrevolver', 'weapon_snspistol_mk2',
                        'weapon_raypistol', 'weapon_minismg', 'weapon_raycarbine', 'weapon_assaultshotgun',
                        'weapon_combatshotgun', 'weapon_heavyshotgun', 'weapon_musket', 'weapon_autoshotgun',
                        'weapon_assaultrifle_mk2', 'weapon_bullpuprifle_mk2', 'weapon_carbinerifle_mk2',
                        'weapon_militaryrifle', 'weapon_specialcarbine_mk2', 'weapon_combatmg', 'weapon_combatmg_mk2',
                        'weapon_mg', 'weapon_heavysniper', 'weapon_heavysniper_mk2', 'weapon_marksmanrifle',
                        'weapon_marksmanrifle_mk2', 'weapon_sniperrifle', 'weapon_grenadelauncher',
                        'weapon_grenadelauncher_smoke', 'weapon_hominglauncher', 'weapon_minigun', 'weapon_railgun',
                        'weapon_rayminigun', 'weapon_snowball'}
